### ISSUE TITLE
tgui bluescreen: `Unable to get property 'cost' of undefined or null reference`

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/TerraGov-Marine-Corps#14230]
### Description

I clicked on whatever tab is above the game preferences in the character setup
```
TypeError: Unable to get property 'cost' of undefined or null reference
   at Anonymous function (http://127.0.0.1:58477/tgui.bundle.js:1:624969)
   at t.GearCustomization (http://127.0.0.1:58477/tgui.bundle.js:1:624939)
```
<details>
<summary>Details</summary>

TypeError: Unable to get property 'cost' of undefined or null reference
   at Anonymous function (http://127.0.0.1:58477/tgui.bundle.js:1:624969)
   at t.GearCustomization (http://127.0.0.1:58477/tgui.bundle.js:1:624939)
   at Be (http://127.0.0.1:58477/tgui.bundle.js:1:161096)
   at Anonymous function (http://127.0.0.1:58477/tgui.bundle.js:1:161364)
   at Le (http://127.0.0.1:58477/tgui.bundle.js:1:161342)
   at Me (http://127.0.0.1:58477/tgui.bundle.js:1:162195)
   at Le (http://127.0.0.1:58477/tgui.bundle.js:1:161206)
   at Me (http://127.0.0.1:58477/tgui.bundle.js:1:162195)
   at Le (http://127.0.0.1:58477/tgui.bundle.js:1:161206)
   at Te (http://127.0.0.1:58477/tgui.bundle.js:1:162390)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"zewaka","interface":"PlayerPreferences","window":{"key":"[0x210026e4]-main","size":null,"fancy":1,"locked":1}}

</details>

### Test Merges

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [23844](https://scrubby.melonmesa.com/round/23844)
BYOND Version: 515.1610
Server revision compiled on: 2023-10-20T20:57:29+00:00
Master commit: [8f96c39f058a8e51f9b1d4c12decda2f8fb39e9c](https://github.com/tgstation/TerraGov-Marine-Corps//commit/8f96c39f058a8e51f9b1d4c12decda2f8fb39e9c)
The following pull requests are currently test merged:
[#13946: 'Adds custom squads' by TiviPlus at commit 42f859fd75](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13946)
[#13924: 'Tweaks widow to be more playable.' by Arturlang at commit 816af28835](https://github.com/tgstation/TerraGov-Marine-Corps//pull/13924)
[#14192: 'throw bounce change' by Lumipharon at commit 8a5c73efa4](https://github.com/tgstation/TerraGov-Marine-Corps//pull/14192)

Local commit: a289339586847bbf3a6c5a104ba4623ad68a2647
Server tools version: 5.16.2

### Reproduction Steps

idk this hasn't happened before, i just clicked the tab

**Comment by vvvv-vvvv** [comment]
#14210
