### ISSUE TITLE
Gear Customization gives BSoD error

### ISSUE THREAD

**Issue by Blank-Cat** [tgstation/TerraGov-Marine-Corps#9899]
### Description

When trying to open gear customization in character preferences, instead of opening it, it returns this error:

TypeError: Unable to get property 'cost' of undefined or null reference
   at Anonymous function (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:493780)
   at t.GearCustomization (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:493750)
   at Be (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:161095)
   at Anonymous function (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:161363)
   at Ie (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:161341)
   at Me (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:162194)
   at Ie (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:161205)
   at Me (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:162194)
   at Ie (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:161205)
   at Te (http://127.0.0.1:63253/tmp10040/tgui.bundle.js:1:162389)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"blankcat","interface":"PlayerPreferences","window":{"key":"[0x2100ab86]-main","size":null,"fancy":1,"locked":0}}

### Test Merges

[#9824: 'Tesla gun rebalance' by goose4429 at commit 38c1559b91](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9824)
[#9772: 'TGUI updates' by TiviPlus at commit 0984f0187b](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9772)
[#9776: 'update atomns init' by TiviPlus at commit 8f37f788e7](https://github.com/tgstation/TerraGov-Marine-Corps//pull/9776)

### Reproduction Steps

1. Open character preferences.
2. Click on gear customization.

### Screenshots

![image](https://user-images.githubusercontent.com/54345929/161412394-fe45835b-cda5-41f4-a39a-a3671a9d01ff.png)

**Comment by BraveMole** [comment]
Duplicate, ask an admin to flush your gear in preferences to fix
